insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('TOYOTA', 'SUPRA','DEPORTIVO','SOY LA DESCRIPCION',69900,10);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('MAZDA', 'RX7','DEPORTIVO','SOY LA DESCRIPCION',48007,15);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('TESLA', 'MODEL 3','VERSACHE','SOY LA DESCRIPCION',49980,12);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('CHEVROLET', 'CAMARO','DEPORTIVO','SOY LA DESCRIPCION',31000,10);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('SEAT', 'LEON','FAMILIAR','SOY LA DESCRIPCION',26490,15);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('FORD', 'FOCUS','FAMILIAR','SOY LA DESCRIPCION',20700,10);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('MERCEDES', 'CLASE E','FAMILIAR','SOY LA DESCRIPCION',52500,10);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('CITROEN', 'C5 ECROSS','FAMILIAR','SOY LA DESCRIPCION',25090,5);

insert into USUARIO (NOMBRE,APELLIDOS,CONTRASEÑA,EMAIL,FECHA_NAC,TARJETA,TITULAR,CODIGO,DIRECCION) values ('Fernando','Correa','$2a$10$tDpZcOD/S9k.eryprYsbkenVqnTheyY4TK05ki1FEfouswEWUkucu','email@email.com','22/08/2001',7814,'Fernando Correa',234,'Calle Falsa 123');
insert into USUARIO (NOMBRE,APELLIDOS,CONTRASEÑA,EMAIL,FECHA_NAC,TARJETA,TITULAR,CODIGO,DIRECCION) values ('admin','admin','$2a$10$lFhL.sRcJewZI3Pt3SiIn.B1gIBjpSlJaJF6rdnTr0ujxKp84HsB.','admin@admin.com','2001-06-19',123456789,'El admin',54321,'Calle ADMIN');

insert into ROL (ID_ROL, NOMBRE_ROL ) values (1, 'ROL_CLIENTE');
insert into ROL (ID_ROL, NOMBRE_ROL ) values (2,'ROL_ADMIN');

insert into USUARIO_ROL (ID_USUARIO, ID_ROL ) values (1,1);
insert into USUARIO_ROL (ID_USUARIO, ID_ROL ) values (2,2);
insert into USUARIO_ROL (ID_USUARIO, ID_ROL ) values (2,1);


