insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA) values ('TOYOTA', 'SUPRA','DEPORTIVO');
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA) values ('MAZDA', 'RX7','DEPORTIVO');
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA) values ('TESLA', 'MODEL 3','VERSACHE');
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA) values ('CITROEN', 'C5 ECROSS','FAMILIAR');

