insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('TOYOTA', 'SUPRA','DEPORTIVO','SOY LA DESCRIPCION',69900,10);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('MAZDA', 'RX7','DEPORTIVO','SOY LA DESCRIPCION',48007,15);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('TESLA', 'MODEL 3','VERSACHE','SOY LA DESCRIPCION',49980,12);
insert into PRODUCTO (MARCA, NOMBRE,CATEGORIA,DESCRIPCION,PRECIO,DESCUENTO) values ('CITROEN', 'C5 ECROSS','FAMILIAR','SOY LA DESCRIPCION',25090,5);

