use springboot_hibernate;

drop database if exists springboot_hibernate;
create database springboot_hibernate;

use springboot_hibernate;

CREATE TABLE PRODUCTO
(
   ID_PRODUCTO BIGINT NOT NULL AUTO_INCREMENT,
   MARCA VARCHAR (40) NOT NULL,
   NOMBRE VARCHAR (40) NOT NULL,
   CATEGORIA VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_PRODUCTO),
   DESCRIPCION VARCHAR (200) NOT NULL,
   PRECIO INT NOT NULL,
   DESCUENTO INT NOT NULL
);

CREATE TABLE USUARIO
(
   ID_USUARIO BIGINT NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR (40) NOT NULL,
   APELLIDOS VARCHAR (40) NOT NULL,
   CONTRASEÑA VARCHAR (40) NOT NULL,
   EMAIL VARCHAR (40) NOT NULL,
   FECHA_NAC VARCHAR(40) NOT NULL, 
   TARJETA INT NOT NULL,
   TITULAR VARCHAR(40) NOT NULL,
   CODIGO INT NOT NULL,
   DIRECCION VARCHAR(40) NOT NULL,
   UNIQUE (NOMBRE),
   PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE PEDIDO
(
	ID_PEDIDO BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR (40) NOT NULL,
	CANTIDAD INT NOT NULL,
	PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (ID_PEDIDO) REFERENCES USUARIO (ID_USUARIO)
);