use springboot_hibernate;

drop database if exists springboot_hibernate;
create database springboot_hibernate;

use springboot_hibernate;

CREATE TABLE PRODUCTO
(
   ID_PRODUCTO BIGINT NOT NULL AUTO_INCREMENT,
   MARCA VARCHAR (40) NOT NULL,
   NOMBRE VARCHAR (40) NOT NULL,
   CATEGORIA VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_PRODUCTO),
   DESCRIPCION VARCHAR (200) NOT NULL,
   PRECIO INT NOT NULL,
   DESCUENTO INT NOT NULL
);

CREATE TABLE IMAGEN
(
	ID_IMAGEN INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR (40) NOT NULL,
	IMAGEN LONGBLOB NOT NULL,
	ID_PRODUCTO BIGINT NOT NULL,
	PRIMARY KEY (ID_IMAGEN),
	CONSTRAINT FK_IMAGEN_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON UPDATE CASCADE
	
);


CREATE TABLE USUARIO
(
   ID_USUARIO BIGINT AUTO_INCREMENT,
   NOMBRE VARCHAR (40) NOT NULL,
   APELLIDOS VARCHAR (40) NOT NULL,
   CONTRASEÑA VARCHAR (140) NOT NULL,
   EMAIL VARCHAR (40) NOT NULL,
   FECHA_NAC VARCHAR(40) NOT NULL, 
   TARJETA INT NOT NULL,
   TITULAR VARCHAR(40) NOT NULL,
   CODIGO INT NOT NULL,
   DIRECCION VARCHAR(40) NOT NULL,
   UNIQUE (NOMBRE),
   PRIMARY KEY (ID_USUARIO)
);


CREATE TABLE COMPRA
(
	ID_COMPRA BIGINT NOT NULL AUTO_INCREMENT,
   	ID_USUARIO BIGINT NOT NULL,
   	PRIMARY KEY (ID_COMPRA),
    CONSTRAINT FK_COMPRA_USAURIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);


CREATE TABLE COMPRA_PRODUCTO
(
	ID_COMPRA BIGINT NOT NULL,
   	ID_PRODUCTO BIGINT NOT NULL,
   	PRIMARY KEY  (
   		ID_COMPRA,
   		ID_PRODUCTO
   	),
    CONSTRAINT FK_COMPRA_PRODUCTO_1 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON UPDATE CASCADE ,
    CONSTRAINT FK_COMPRA_PRODUCTO_2 FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA)
);

CREATE TABLE ROL
(
   ID_ROL BIGINT AUTO_INCREMENT,
   NOMBRE_ROL VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO_ROL
(
   ID_USUARIO BIGINT NOT NULL,
   ID_ROL BIGINT,
      PRIMARY KEY
   (
      ID_USUARIO,
      ID_ROL
   ),
   CONSTRAINT FK_USUARIO_ROL_1 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE,
   CONSTRAINT FK_USUARIO_ROL_2 FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE PREGUNTA
(
	ID_PREGUNTA INT NOT NULL AUTO_INCREMENT,
	TEXTOPREGUNTA VARCHAR (100) NOT NULL,
	FECHAPREGUNTA VARCHAR (30) NOT NULL,
	ID_PRODUCTO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	PRIMARY KEY (ID_PREGUNTA),
	CONSTRAINT FK_PREGUNTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON UPDATE CASCADE,
	CONSTRAINT FK_PREGUNTA_USAURIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON UPDATE CASCADE
);


CREATE TABLE PEDIDO
(
	ID_PEDIDO BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR (40) NOT NULL,
	CANTIDAD INT NOT NULL,
	PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (ID_PEDIDO) REFERENCES USUARIO (ID_USUARIO)
);